// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const isProduction = process.env["NODE_ENV"] === "production";

// Production: prefer the direct connection (migrations need advisory locks, which PgBouncer doesn't support)
const databaseUrl = isProduction
  ? (process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"])
  : process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
