/**
 * Wikipedia language-edition subdomain → English language name, keyed
 * lowercase. The `country` column holds this subdomain for wiki traffic (see
 * data-collector/get-language-from-server-url.ts), so "ar" is Arabic, not
 * Argentina — which is why these codes must never be read as ISO 3166.
 *
 * Generated from the Wikimedia site matrix (every Wikipedia edition, closed
 * ones included, so older events still get a name):
 * https://meta.wikimedia.org/w/api.php?action=sitematrix&smtype=language&smstate=all
 */
export const WIKI_LANGUAGE_NAMES: Record<string, string> = {
  aa: "Afar",
  ab: "Abkhazian",
  ace: "Acehnese",
  ady: "Adyghe",
  af: "Afrikaans",
  ak: "Akan",
  als: "Alemannic",
  alt: "Southern Altai",
  am: "Amharic",
  ami: "Amis",
  an: "Aragonese",
  ang: "Old English",
  ann: "Obolo",
  anp: "Angika",
  ar: "Arabic",
  arc: "Aramaic",
  ary: "Moroccan Arabic",
  arz: "Egyptian Arabic",
  as: "Assamese",
  ast: "Asturian",
  atj: "Atikamekw",
  av: "Avaric",
  avk: "Kotava",
  awa: "Awadhi",
  ay: "Aymara",
  az: "Azerbaijani",
  azb: "South Azerbaijani",
  ba: "Bashkir",
  ban: "Balinese",
  bar: "Bavarian",
  "bat-smg": "Samogitian",
  bbc: "Batak Toba",
  bcl: "Central Bikol",
  bdr: "West Coast Bajau",
  be: "Belarusian",
  "be-tarask": "Belarusian (Taraškievica orthography)",
  bew: "Betawi",
  bg: "Bulgarian",
  bh: "Bhojpuri",
  bi: "Bislama",
  bjn: "Banjar",
  blk: "Pa'O",
  bm: "Bambara",
  bn: "Bangla",
  bo: "Tibetan",
  bol: "Bole",
  bpy: "Bishnupriya",
  br: "Breton",
  bs: "Bosnian",
  btm: "Batak Mandailing",
  bug: "Buginese",
  bxr: "Russia Buriat",
  ca: "Catalan",
  "cbk-zam": "Chavacano",
  cdo: "Mindong",
  ce: "Chechen",
  ceb: "Cebuano",
  ch: "Chamorro",
  cho: "Choctaw",
  chr: "Cherokee",
  chy: "Cheyenne",
  ckb: "Central Kurdish",
  co: "Corsican",
  cr: "Cree",
  crh: "Crimean Tatar",
  cs: "Czech",
  csb: "Kashubian",
  cu: "Church Slavic",
  cv: "Chuvash",
  cy: "Welsh",
  da: "Danish",
  dag: "Dagbani",
  de: "German",
  dga: "Southern Dagaare",
  din: "Dinka",
  diq: "Dimli",
  dsb: "Lower Sorbian",
  dtp: "Central Dusun",
  dty: "Doteli",
  dv: "Divehi",
  dz: "Dzongkha",
  ee: "Ewe",
  el: "Greek",
  eml: "Emiliano-Romagnolo",
  en: "English",
  eo: "Esperanto",
  es: "Spanish",
  et: "Estonian",
  eu: "Basque",
  ext: "Extremaduran",
  fa: "Persian",
  fat: "Fanti",
  ff: "Fula",
  fi: "Finnish",
  "fiu-vro": "Võro",
  fj: "Fijian",
  fo: "Faroese",
  fon: "Fon",
  fr: "French",
  frp: "Arpitan",
  frr: "Northern Frisian",
  fur: "Friulian",
  fy: "Western Frisian",
  ga: "Irish",
  gag: "Gagauz",
  gan: "Gan",
  gcr: "Guianan Creole",
  gd: "Scottish Gaelic",
  gl: "Galician",
  glk: "Gilaki",
  gn: "Guarani",
  gom: "Goan Konkani",
  gor: "Gorontalo",
  got: "Gothic",
  gpe: "Ghanaian Pidgin",
  gu: "Gujarati",
  guc: "Wayuu",
  gur: "Frafra",
  guw: "Gun",
  gv: "Manx",
  ha: "Hausa",
  hak: "Hakka Chinese",
  haw: "Hawaiian",
  he: "Hebrew",
  hi: "Hindi",
  hif: "Fiji Hindi",
  ho: "Hiri Motu",
  hr: "Croatian",
  hsb: "Upper Sorbian",
  ht: "Haitian Creole",
  hu: "Hungarian",
  hy: "Armenian",
  hyw: "Western Armenian",
  hz: "Herero",
  ia: "Interlingua",
  iba: "Iban",
  id: "Indonesian",
  ie: "Interlingue",
  ig: "Igbo",
  igl: "Igala",
  ii: "Sichuan Yi",
  ik: "Inupiaq",
  ilo: "Iloko",
  inh: "Ingush",
  io: "Ido",
  is: "Icelandic",
  isv: "Interslavic",
  it: "Italian",
  iu: "Inuktitut",
  ja: "Japanese",
  jam: "Jamaican Creole English",
  jbo: "Lojban",
  jv: "Javanese",
  ka: "Georgian",
  kaa: "Kara-Kalpak",
  kab: "Kabyle",
  kai: "Karekare",
  kaj: "Jju",
  kbd: "Kabardian",
  kbp: "Kabiye",
  kcg: "Tyap",
  kg: "Kongo",
  kge: "Komering",
  ki: "Kikuyu",
  kj: "Kuanyama",
  kk: "Kazakh",
  kl: "Kalaallisut",
  km: "Khmer",
  kn: "Kannada",
  knc: "Central Kanuri",
  ko: "Korean",
  koi: "Komi-Permyak",
  kr: "Kanuri",
  krc: "Karachay-Balkar",
  ks: "Kashmiri",
  ksh: "Colognian",
  ku: "Kurdish",
  kus: "Kusaal",
  kv: "Komi",
  kw: "Cornish",
  ky: "Kyrgyz",
  la: "Latin",
  lad: "Ladino",
  lb: "Luxembourgish",
  lbe: "Lak",
  lez: "Lezghian",
  lfn: "Lingua Franca Nova",
  lg: "Ganda",
  li: "Limburgish",
  lij: "Ligurian",
  lld: "Ladin",
  lmo: "Lombard",
  ln: "Lingala",
  lo: "Lao",
  lrc: "Northern Luri",
  lt: "Lithuanian",
  ltg: "Latgalian",
  lv: "Latvian",
  mad: "Madurese",
  mag: "Magahi",
  mai: "Maithili",
  "map-bms": "Banyumasan",
  mdf: "Moksha",
  mg: "Malagasy",
  mh: "Marshallese",
  mhr: "Eastern Mari",
  mi: "Māori",
  min: "Minangkabau",
  mk: "Macedonian",
  ml: "Malayalam",
  mn: "Mongolian",
  mni: "Manipuri",
  mnw: "Mon",
  mos: "Mossi",
  mr: "Marathi",
  mrj: "Western Mari",
  ms: "Malay",
  mt: "Maltese",
  mus: "Muscogee",
  mwl: "Mirandese",
  my: "Burmese",
  myv: "Erzya",
  mzn: "Mazanderani",
  na: "Nauru",
  nah: "Nahuatl",
  nap: "Neapolitan",
  nds: "Low German",
  "nds-nl": "Low Saxon",
  ne: "Nepali",
  new: "Newari",
  ng: "Ndonga",
  nia: "Nias",
  nl: "Dutch",
  nn: "Norwegian Nynorsk",
  no: "Norwegian",
  nov: "Novial",
  nqo: "N’Ko",
  nr: "South Ndebele",
  nrm: "Norman",
  nso: "Northern Sotho",
  nup: "Nupe",
  nv: "Navajo",
  ny: "Nyanja",
  oc: "Occitan",
  olo: "Livvi-Karelian",
  om: "Oromo",
  or: "Odia",
  os: "Ossetic",
  pa: "Punjabi",
  pag: "Pangasinan",
  pam: "Pampanga",
  pap: "Papiamento",
  pcd: "Picard",
  pcm: "Nigerian Pidgin",
  pdc: "Pennsylvania German",
  pfl: "Palatine German",
  pi: "Pali",
  pih: "Pitcairn-Norfolk",
  pl: "Polish",
  pms: "Piedmontese",
  pnb: "Western Punjabi",
  pnt: "Pontic",
  ppl: "Nawat",
  ps: "Pashto",
  pt: "Portuguese",
  pwn: "Paiwan",
  qu: "Quechua",
  rki: "Arakanese",
  rm: "Romansh",
  rmy: "Vlax Romani",
  rn: "Rundi",
  ro: "Romanian",
  "roa-rup": "Aromanian",
  "roa-tara": "Tarantino",
  rsk: "Pannonian Rusyn",
  ru: "Russian",
  rue: "Rusyn",
  rw: "Kinyarwanda",
  sa: "Sanskrit",
  sah: "Yakut",
  sat: "Santali",
  sc: "Sardinian",
  scn: "Sicilian",
  sco: "Scots",
  sd: "Sindhi",
  se: "Northern Sami",
  sg: "Sango",
  sh: "Serbo-Croatian",
  shi: "Tachelhit",
  shn: "Shan",
  si: "Sinhala",
  simple: "Simple English",
  sk: "Slovak",
  skr: "Saraiki",
  sl: "Slovenian",
  sm: "Samoan",
  smn: "Inari Sami",
  sn: "Shona",
  so: "Somali",
  sq: "Albanian",
  sr: "Serbian",
  srn: "Sranan Tongo",
  ss: "Swati",
  st: "Southern Sotho",
  stq: "Saterland Frisian",
  su: "Sundanese",
  sv: "Swedish",
  sw: "Swahili",
  syl: "Sylheti",
  szl: "Silesian",
  szy: "Sakizaya",
  ta: "Tamil",
  tay: "Atayal",
  tcy: "Tulu",
  tdd: "Tai Nuea",
  te: "Telugu",
  tet: "Tetum",
  tg: "Tajik",
  th: "Thai",
  ti: "Tigrinya",
  tig: "Tigre",
  tk: "Turkmen",
  tl: "Tagalog",
  tly: "Talysh",
  tn: "Tswana",
  to: "Tongan",
  tok: "Toki Pona",
  tpi: "Tok Pisin",
  tr: "Turkish",
  trv: "Taroko",
  ts: "Tsonga",
  tt: "Tatar",
  tum: "Tumbuka",
  tw: "Twi",
  ty: "Tahitian",
  tyv: "Tuvinian",
  udm: "Udmurt",
  ug: "Uyghur",
  uk: "Ukrainian",
  ur: "Urdu",
  uz: "Uzbek",
  ve: "Venda",
  vec: "Venetian",
  vep: "Veps",
  vi: "Vietnamese",
  vls: "West Flemish",
  vo: "Volapük",
  wa: "Walloon",
  war: "Waray",
  wo: "Wolof",
  wuu: "Wu",
  xal: "Kalmyk",
  xh: "Xhosa",
  xmf: "Mingrelian",
  yi: "Yiddish",
  yo: "Yoruba",
  za: "Zhuang",
  zea: "Zeelandic",
  zgh: "Standard Moroccan Tamazight",
  zh: "Chinese",
  "zh-classical": "Literary Chinese",
  "zh-min-nan": "Minnan",
  "zh-yue": "Cantonese",
  zu: "Zulu",
};
